name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.1.0
homepage: https://github.com/Arbify/arbify_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dio: ^5.1.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  intl_utils: ^2.1.0
  path: ^1.8.0
  petitparser: ^5.0.0
  universal_io: ^2.0.3
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.1
  lint: ^2.0.1
  mockito: ^5.0.3
  test: ^1.16.8
